import type { Metadata } from "next";
import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";


const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Eccomerce Website",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight:['400' , '700'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
       
        {children}
       <Footer/>
        </body>
    </html>
  );
}
