import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

import type { Metadata } from "next";
import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Providers from "./provider";
import TopBar from './components/navbar';


const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Eccomerce Website",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight:['400' , '700'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    // <html lang="en">
    //   <body className={poppins.className}>
    //    <Providers>
    //     {children}
    //    <Footer/>
    //    </Providers>
    //     </body>
    // </html>

    <ClerkProvider>
      <html lang="en">
        <body>
          {/* <SignedOut>
            <SignInButton />
          </SignedOut> */}
          {/* <SignedIn>
            <UserButton />
          </SignedIn> */}
          <Providers>
          {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
    
  );
}
