
// const Products = [
//   {
//     id: 1,
//     title: "Vel elit euismod",
//     image: ["/ground.png", "/ground.png"],
//     slug: "Vel elit euismod",
//     price: 150,
//     discount: 0,
//     category: "tops",
//     description:
//       "Best quality chairs for office and homes",
//     size: ["S", "M", "L", "XL"],
//     color: ["#ffffff", "#000000", "#e60000"],
//     qty: 1,
//   },
//     {
//       id: 2,
//       title: "Ultricies condimentum imperdiet",
//       image: ["/ponky.png"],
//       slug: "Ultricies condimentum imperdiet",
//       price: 200,
//       discount: 50,
//       category: "paints",
//       description:
//         "Best quality sofas for home and offices",
//       size: ["S", "M", "XL"],
//       color: ["#fafafa", "#000000", "#e60000"],
//       qty: 1,
//     },
  
//     {
//       id: 3,
//       title: "Vitae suspendisse sed",
//       image: ["/wall.png"],
//       slug: "Vitae suspendisse sed",
//       price: 150,
//       discount: 40,
//       category: "shoes",
//       description:
//         "Top Notch Shoes. ",
//       size: ["5", "6", "6.5", "7.5", "8.5", "9"],
//       color: ["#ffffff", "#000000", "#e60000"],
//       qty: 1,
//     },
  
//     {
//       id: 4,
//       title: "Sed at fermentum",
//       image: ["/school.png"],
//       slug: "Sed at fermentum",
//       price: 150,
//       discount: 0,
//       category: "shoes",
//       description:
//         "Top Notch Watch. ",
//       size: ["5", "6", "6.5", "7.5", "8.5", "9"],
//       color: ["#000000"],
//       qty: 1,
//     },
  
  
//     {
//       id: 5,
//       title: "Fusce pellentesque at",
//       image: ["/hand.png", "/wall.png"],
//       slug: "Fusce pellentesque at",
//       price: 2500,
//       discount: 0,
//       category: "accessories",
//       description:
//         "Top Notch Jewellery. ",
//       size: ["free size"],
//       color: ["#ffffff", "#000000", "#e60000"],
//       qty: 1,
//     },
//     {
//       id: 6,
//       title: "Vestibulum magna laoreet",
//       image: ["/clock.png", "/clock.png"],
//       slug: "Vestibulum magna laoreet",
//       price: 100,
//       discount: 0,
//       category: "tops",
//       description:
//         "Best quality tshirt for women",
//       size: ["S", "L"],
//       color: ["#ffffff", "#000000", "#e60000"],
//       qty: 1,
//     },
//     {
//       id: 7,
//       title: "Sollicitudin amet orci",
//       image: ["/bluesofa.png"],
//       slug: "Sollicitudin amet orci",
//       price: 1500,
//       discount: 0,
//       category: "tops",
//       description:
//         "Best quality sofas for home and offices",
//       size: ["S", "M", "XL"],
//       color: ["#ffffff", "#000000", "#e60000"],
//       qty: 1,
//     },
//     {
//       id: 8,
//       title: "Ultrices mauris sit",
//       image: [
//         "/head.png",
//         "/head.png",
//         "/head.png",
//       ],
//       slug: "Ultrices mauris sit",
//       price: 350,
//       discount: 0,
//       category: "tops",
//       description:
//         "Best quality tshirt for women",
//         size: ["S", "L"],
//       color: ["#ffffff", "#000000", "#e60000"],
//       qty: 1,
//     },
//     {
//       id: 9,
//       title: "Pellentesque condimentum ac",
//       image: ["/band.png", "/band.png"],
//       slug: "Pellentesque condimentum ac",
//       price: 400,
//       discount: 60,
//       category: "tops",
//       description:
//         "Best quality shirt for women",
//       size: ["M", "L"],
//       color: ["#ffffff", "#becfd6"],
//       qty: 1,
//     },
  
//   //   Acessories and jewellery
//     {
//       id: 10,
//       title: "Cras scelerisque velit",
//       image: ["/camera.png", "/camera.png"],
//       slug: "Cras scelerisque velit",
//       price: 2500,
//       discount: 30,
//       category: "accessories",
//       description:
//         "Top Notch glasses",
//       size: ["free size"],
//       color: ["#ffffff", "#000000", "#e60000"],
//       qty: 1,
//     },
//     {
//       id: 11,
//       title: "Lectus vulputate faucibus",
//       image: [
//         "/purple.png",
//         "/purple.png",
//         "/purple.png",
//       ],
//       slug: "Lectus vulputate faucibus",
//       price: 150,
//       discount: 0,
//       category: "paints",
//       description:
//         "Best quality Headset for womens",
//       size: ["S", "M", "XL"],
//       color: ["#fafafa", "#000000", "#e60000"],
//       qty: 1,
//     }, 
//     {
//       id: 11,
//       title: "Lectus vulputate faucibus",
//       image: [
//         "/purple.png",
//         "/purple.png",
//         "/purple.png",
//       ],
//       slug: "Lectus vulputate faucibus",
//       price: 150,
//       discount: 0,
//       category: "paints",
//       description:
//         "Best quality Headset for womens",
//       size: ["S", "M", "XL"],
//       color: ["#fafafa", "#000000", "#e60000"],
//       qty: 1,
//     }, 
    
//   ]
//   export default Products;






const Products = [
  {
    id: 1,
    title: "Vel elit euismod",
    image: ["/ground.png", "/ground.png"],
    slug: "vel-elit-euismod",
    price: 150,
    discount: 0,
    category: "tops",
    description: "Best quality chairs for office and homes",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
  },
  {
    id: 2,
    title: "Ultricies condimentum imperdiet",
    image: ["/ponky.png"],
    slug: "ultricies-condimentum-imperdiet",
    price: 200,
    discount: 50,
    category: "paints",
    description: "Best quality sofas for home and offices",
    size: ["S", "M", "XL"],
    color: ["#fafafa", "#000000", "#e60000"],
    qty: 1,
  },
  {
    id: 3,
    title: "Vitae suspendisse sed",
    image: ["/wall.png"],
    slug: "vitae-suspendisse-sed",
    price: 150,
    discount: 40,
    category: "shoes",
    description: "Top-notch shoes.",
    size: ["5", "6", "6.5", "7.5", "8.5", "9"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
  },
  {
    id: 4,
    title: "Sed at fermentum",
    image: ["/school.png"],
    slug: "sed-at-fermentum",
    price: 150,
    discount: 0,
    category: "shoes",
    description: "Top-notch watch.",
    size: ["5", "6", "6.5", "7.5", "8.5", "9"],
    color: ["#000000"],
    qty: 1,
  },
  {
    id: 5,
    title: "Fusce pellentesque at",
    image: ["/hand.png", "/wall.png"],
    slug: "fusce-pellentesque-at",
    price: 2500,
    discount: 0,
    category: "accessories",
    description: "Top-notch jewellery.",
    size: ["free size"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
  },
  {
    id: 6,
    title: "Vestibulum magna laoreet",
    image: ["/clock.png", "/clock.png"],
    slug: "vestibulum-magna-laoreet",
    price: 100,
    discount: 0,
    category: "tops",
    description: "Best quality t-shirt for women.",
    size: ["S", "L"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
  },
  {
    id: 7,
    title: "Sollicitudin amet orci",
    image: ["/bluesofa.png"],
    slug: "sollicitudin-amet-orci",
    price: 1500,
    discount: 0,
    category: "tops",
    description: "Best quality sofas for home and offices.",
    size: ["S", "M", "XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
  },
  {
    id: 8,
    title: "Ultrices mauris sit",
    image: ["/head.png", "/head.png", "/head.png"],
    slug: "ultrices-mauris-sit",
    price: 350,
    discount: 0,
    category: "tops",
    description: "Best quality t-shirt for women.",
    size: ["S", "L"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
  },
  {
    id: 9,
    title: "Pellentesque condimentum ac",
    image: ["/band.png", "/band.png"],
    slug: "pellentesque-condimentum-ac",
    price: 400,
    discount: 60,
    category: "tops",
    description: "Best quality shirt for women.",
    size: ["M", "L"],
    color: ["#ffffff", "#becfd6"],
    qty: 1,
  },
  {
    id: 10,
    title: "Cras scelerisque velit",
    image: ["/camera.png", "/camera.png"],
    slug: "cras-scelerisque-velit",
    price: 2500,
    discount: 30,
    category: "accessories",
    description: "Top-notch glasses.",
    size: ["free size"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
  },
  {
    id: 11,
    title: "Lectus vulputate faucibus",
    image: ["/purple.png", "/purple.png", "/purple.png"],
    slug: "lectus-vulputate-faucibus",
    price: 150,
    discount: 0,
    category: "paints",
    description: "Best quality headset for women.",
    size: ["S", "M", "XL"],
    color: ["#fafafa", "#000000", "#e60000"],
    qty: 1,
  },
  {
    id: 12,
    title: "Lectus faucibus",
    image: ["/chair5.png","/chair5.png","/chair5.png"],
    slug: "lectus-faucibus",
    price: 150,
    discount: 0,
    category: "paints",
    description: "Best quality chair for home.",
    size: ["S", "M", "XL"],
    color: ["#fafafa", "#000000", "#e60000"],
    qty: 1,
  },
];

export default Products;
