
const Products = [
  {
    id: 1,
    title: "Yellow Women Printed Tee",
    image: ["/ground.png", "/ground.png"],
    slug: "Red-women-printed-tee",
    price: 150,
    discount: 0,
    category: "tops",
    description:
      "Best quality tshirt for women",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
  },
    {
      id: 2,
      title: "Black Denim For Women",
      image: ["/ponky.png"],
      slug: "black-denim-for-women",
      price: 200,
      discount: 50,
      category: "paints",
      description:
        "Best quality pant denim for women",
      size: ["S", "M", "XL"],
      color: ["#fafafa", "#000000", "#e60000"],
      qty: 1,
    },
  
    {
      id: 3,
      title: "Super Sneakers",
      image: ["/wall.png"],
      slug: "Super-Sneakers",
      price: 150,
      discount: 40,
      category: "shoes",
      description:
        "Top Notch Shoes. ",
      size: ["5", "6", "6.5", "7.5", "8.5", "9"],
      color: ["#ffffff", "#000000", "#e60000"],
      qty: 1,
    },
  
    {
      id: 4,
      title: "Black Pumpees",
      image: ["/school.png"],
      slug: "black-pumpees",
      price: 150,
      discount: 0,
      category: "shoes",
      description:
        "Top Notch Shoes. ",
      size: ["5", "6", "6.5", "7.5", "8.5", "9"],
      color: ["#000000"],
      qty: 1,
    },
  
  
    {
      id: 5,
      title: "Gucci Black Purse",
      image: ["/hand.png", "/wall.png"],
      slug: "Gucci-Black-Purse",
      price: 2500,
      discount: 0,
      category: "accessories",
      description:
        "Top Notch Jewellery. ",
      size: ["free size"],
      color: ["#ffffff", "#000000", "#e60000"],
      qty: 1,
    },
    {
      id: 6,
      title: "White Women Printed Tee",
      image: ["/clock.png", "/clock.png"],
      slug: "white-women-printed-tee",
      price: 100,
      discount: 0,
      category: "tops",
      description:
        "Best quality tshirt for women",
      size: ["S", "L"],
      color: ["#ffffff", "#000000", "#e60000"],
      qty: 1,
    },
    {
      id: 7,
      title: "Overcoat",
      image: ["/bluesofa.png"],
      slug: "gray-overcoat",
      price: 1500,
      discount: 0,
      category: "tops",
      description:
        "Best quality tshirt for women",
      size: ["S", "M", "XL"],
      color: ["#ffffff", "#000000", "#e60000"],
      qty: 1,
    },
    {
      id: 8,
      title: "Amazing Printed Tees",
      image: [
        "/head.png",
        "/head.png",
        "/head.png",
      ],
      slug: "amazing-printed-tees",
      price: 350,
      discount: 0,
      category: "tops",
      description:
        "Best quality tshirt for women",
        size: ["S", "L"],
      color: ["#ffffff", "#000000", "#e60000"],
      qty: 1,
    },
    {
      id: 9,
      title: "Shirt For Women",
      image: ["/band.png", "/band.png"],
      slug: "shirt-for-women",
      price: 400,
      discount: 60,
      category: "tops",
      description:
        "Best quality shirt for women",
      size: ["M", "L"],
      color: ["#ffffff", "#becfd6"],
      qty: 1,
    },
  
  //   Acessories and jewellery
    {
      id: 10,
      title: "Raybon Glasses",
      image: ["/camera.png", "/camera.png"],
      slug: "raybon-glasses",
      price: 2500,
      discount: 30,
      category: "accessories",
      description:
        "Top Notch glasses",
      size: ["free size"],
      color: ["#ffffff", "#000000", "#e60000"],
      qty: 1,
    },
    {
      id: 11,
      title: "Hand Stitch Trousers",
      image: [
        "/purple.png",
        "/purple.png",
        "/purple.png",
      ],
      slug: "hand-stitch-trousers",
      price: 150,
      discount: 0,
      category: "paints",
      description:
        "Best quality trousers for women",
      size: ["S", "M", "XL"],
      color: ["#fafafa", "#000000", "#e60000"],
      qty: 1,
    },
    {
        id: 11,
        title: "Hand Stitch Trousers",
        image: [
          "/wall.png",
          "/wall.png",
          "/wall.png",
        ],
        slug: "hand-stitch-trousers",
        price: 150,
        discount: 0,
        category: "paints",
        description:
          "Best quality trousers for women",
        size: ["S", "M", "XL"],
        color: ["#fafafa", "#000000", "#e60000"],
        qty: 1,
      },
  ]
  export default Products;